m1923: Patch qti-telephony-common.jar to include needed classes
msg: java.lang.ClassNotFoundException: android.hidl.manager.V1_0.IServiceNotification
stacktrace: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/hidl/manager/V1_0/IServiceNotification;
	at com.qualcomm.qti.internal.telephony.QtiTelephonyComponentFactory.makeRIL(QtiTelephonyComponentFactory.java:202)
	at com.android.internal.telephony.PhoneFactory.makeDefaultPhone(PhoneFactory.java:167)
	at com.android.internal.telephony.PhoneFactory.makeDefaultPhones(PhoneFactory.java:103)
	at com.android.phone.PhoneGlobals.onCreate(PhoneGlobals.java:340)
	at com.android.phone.PhoneApp.onCreate(PhoneApp.java:39)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
	at android.app.ActivityThread.access(ActivityThread.java:219)
	at android.app.ActivityThread.handleMessage(ActivityThread.java:1859)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
Caused by: java.lang.ClassNotFoundException: android.hidl.manager.V1_0.IServiceNotification
	... 15 more